apiVersion: v1
kind: Service
metadata:
  name: todo-node-app-service
  namespace: test
  labels:
    app: todo-node-app
spec:
  type: ClusterIP              
  selector:
    app: todo-node-app             # Must match your Deployment's pod label
  ports:
    - protocol: TCP
      port: 8000                 # Service port inside the cluster
      targetPort: 8000         # Container port exposed by app
